const tasks = [
  {
    id: "0",
    title: "Reading Books",
    Date: "2023/10/01",
    category: "Read",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "50 minutes",
  },
  {
    id: "1",
    title: "Editing Audio",
    Date: "2023/10/01",
    category: "Entertainment",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "75 minutes",
  },
  {
    id: "2",
    title: "Learn Programming",
    Date: "2023/10/01",
    category: "Code",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "50 minutes",
  },
  {
    id: "3",
    title: "Dumbell Excercise",
    Date: "2023/10/01",
    category: "Gym",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "25 minutes",
  },
  {
    id: "4",
    title: "Tech Exploration",
    Date: "2023/10/01",
    category: "Technology",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "50 minutes",
  },
  {
    id: "5",
    title: "Tech Exploration 2",
    Date: "2023/10/01",
    category: "Technology",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "50 minutes",
  },
  {
    id: "6",
    title: "Tech Exploration 3",
    Date: "2023/10/01",
    category: "Technology",
    sessions: 4,
    longBreaks: 2,
    shortBreaks: 3,
    time: "50 minutes",
  },
];

export default tasks;
